trigger:
- dev

variables:
  imageName: dashboardapi

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        containerRegistry: 'crsantechdev-Dev'
        repository: 'dashboardapi'
        command: 'buildAndPush'
        Dockerfile: '**/DashboardApi/Dockerfile'
        tags: |
          latest

- stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployApp
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'DevOps-AzureSponsored'
        appName: 'eit-factory-ops-dashboard'
        containers: 'crsantechdev-dnerh8h2gne6g8f0.azurecr.io/dashboardapi:latest'
